src/jira/tickets.rs

(I think it should work, I haven't tested it but it looks right to me)

fix 🔧: Clean up get_comments code

---

Cargo.lock
Cargo.toml
src/app.rs
src/jira.rs
src/jira/projects.rs
src/widgets/projects.rs
src/widgets/tickets.rs

fix: #32
fix: #33
fix: #34
Add pagination for tickets.  Fixed surrealDB query to return tickets when needed in relation to project.

32: Add pagination for tickets

---

Cargo.lock
Cargo.toml
README.md
src/app.rs
src/jira/tickets.rs
src/widgets/comments_add.rs

61: Remove all info blocks

---

Cargo.lock
Cargo.toml
README.md
src/app.rs
src/jira.rs

63: Fix ticket transition update

---

Cargo.lock
Cargo.toml
README.md
src/app.rs
src/widgets/commands.rs

65: Add help and document browser action

---

Cargo.lock
Cargo.toml
README.md
src/app.rs
src/widgets/comments.rs

49: Combine comments list and view

---

Cargo.lock
Cargo.toml
README.md
src/app.rs
src/widgets/comments.rs
src/widgets/comments_add.rs

50: Move comment add action to comment list pane

---

.gitignore
Cargo.lock
Cargo.toml
README.md
sample.toml
src/config.rs

24: Add config file

---

Cargo.lock
Cargo.toml
README.md
sample.toml
src/app.rs
src/config.rs
src/jira.rs
src/jira/tickets.rs
src/widgets/tickets.rs

75: Add config for current user tickets

---

Cargo.lock
Cargo.toml
README.md
sample.toml
src/app.rs
src/config.rs
src/jira.rs

46: Add option to use file based cache

---

.gitignore
Cargo.lock
Cargo.toml
README.md
src/app.rs
src/jira.rs
src/jira/tickets.rs
src/widgets/parent.rs
src/widgets/ticket_relation.rs
src/widgets/tickets.rs

fix: #97
fix: #23
use open browser method to open a browser tab for related ticket and parent ticket

97: Open parent ticket from parent pane

---

Cargo.lock
Cargo.toml
sample.toml
src/config.rs
src/jira.rs

close: #111
Add option to view current sprint tickets only.

111: Add option to view current sprint tickets

---

README.md
sample.toml
src/config.rs
src/widgets/comments.rs
src/widgets/help.rs

these were already being read but discarded

use api_key and api_version from config.toml

---

Dockerfile
compose.yaml

docker compose run --rm rust cargo build

add container-based dev workflow

---

Cargo.lock
Cargo.toml
src/jira/tickets.rs

Remove custom_id field from serde

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
src/app.rs
src/config.rs
src/jira.rs
src/jira/projects.rs
src/jira/tickets.rs
src/widgets/parent.rs
src/widgets/ticket_transition.rs

Fix custom fields lookup

---

.github/workflows/tag-bump.yml

Remove prerelease

---

.github/workflows/publish.yml
.github/workflows/tag-bump.yml

Add PAT for release

---

.github/workflows/publish.yml
.github/workflows/tag-bump.yml

Add token for bump

---

.github/workflows/publish.yml
.github/workflows/tag-bump.yml

Set github to pat

---

.github/workflows/tag-bump.yml

Change secret name

---

.github/workflows/pr.yml
.github/workflows/publish.yml
src/widgets/ticket_transition.rs

Update actions for PR only

---

.github/workflows/publish.yml
.github/workflows/tag-bump.yml

Actions install cargo-bump

---

src/jira.rs

Remove: Past and future sprint restriction
fix: #144 #patch

Remove past and future sprint restriction

---

Cargo.lock
Cargo.toml
src/app.rs
src/jira.rs
src/jira/auth.rs
src/jira/tickets.rs

#patch
For whatever reason, there's a task to update project during ticket transition.  This method gets stuck when transitioning ticket and thus is now removed from transition.
fix: Ticket transition bug

Fix ticket transition bug
